image: ruby:latest
cache:
  paths:
    - src/vendor/ruby
    - src/_site

build-job:
  stage: build
  variables:
    JEKYLL_ENV: "production"
  script:
    - cd src
    - bundle config set path 'vendor' # Install dependencies into src/vendor/ruby
    - bundle install -j $(nproc)
    - rake build

# Maybe there's a better container for this job
deploy-s3:
  stage: deploy
  script:
    - apt-get update
    - apt-get install --no-install-recommends -y awscli
    - aws s3 cp src/_site/ s3://egee.xyz --recursive --acl=public-read
  only:
    - master
