cache:
  paths:
    - src/vendor/ruby
    - src/_site

build-job:
  image: ruby:3.0
  stage: build
  variables:
    JEKYLL_ENV: "production"
  before_script:
    - cd src
    - bundle config set path 'vendor' # Install dependencies into src/vendor/ruby
    - bundle install -j $(nproc)
  script:
    - rake build

deploy-s3:
  image: amazon/aws-cli:2.5
  stage: deploy
  script:
    - aws s3 cp src/_site/ s3://egee.io --recursive --acl=public-read
  only:
    - master
