language: ruby
rvm:
  - 2.5
before_install:
  - gem install bundler

# Default script	rake

script:
  - bundle exec jekyll build
deploy:
  - provider: script
    skip_cleanup: true
    # script: bash terraform.sh apply -auto-approve
    # on:
    #   tags: true