language: ruby
cache: bundler
script: rake build
deploy:
  provider: s3
  access_key_id: "${ACCESS}"
  secret_access_key: "${KEY}"
  bucket: "egee.io"
  acl: public_read
  local_dir: _site
  skip_cleanup: true
  edge: true
