language: ruby
rvm:
  - 2.5
before_install:
  - gem install bundler

# Default script	rake

script:
  - bundle exec jekyll build
deploy:
  - provider: script
    skip_cleanup: true
    script: rsync $rsync_args "$rsync_args" ./_site/* $conn_str:$deploy_path
    # on:
    #   tags: true