language: ruby
rvm:
  - 2.5
before_install:
  - gem install bundler

# Default script	rake

script:
  - bundle exec jekyll build
after_script:
  - echo $my_key | base64 -d > ./my_key
  - ls -la
# deploy:
#   - provider: script
#     skip_cleanup: true
#     script: rsync $rsync_args "$rsync_args" ./_site/* $conn_str:$deploy_path
    # on:
    #   tags: true