basic_settings:
  site_title: Egee.io
  favicon_image: /images/favicon.ico

header_settings:
  logo_image: 
  logo_width: 200

menu_settings:
  menu_items:
    - title: 'Blog'
      url: 'https://medium.com/@egee_irl'

footer_settings:
  footer_tagline: Be different. Play together.

hero_settings:
  overlay_opacity: 0.8

post_settings:
  grid_spacing: 10

contact_settings:
  form_action: 'https://formspree.io/'
  confirmation_url: '/thanks'
  email_subject: 'Contact form submission'
  send_button_text: 'Send Message'

social_settings:
  discord_url: 'https://discord.gg/EMbcgR8'
  youtube_url: 'https://www.youtube.com/c/Egeeirl'
  github_url: 'https://github.com/Egeeio'

color_settings:
  background_color: '#273359'
  background_alt_color: '#9e4e19'
  text_dark_color: '#ffffff'
  text_medium_color: '#ffffff'
  text_light_color: '#ffffff'
  accent_color: '#3498db'
  border_color: '#dddddd'
  hero_background_color: '#14191E'
  # hero_background_color: '#4f637a'
  # hero_background_color: '#110C03'
  hero_text_color: '#ffffff'
  error_color: '#D64541'

font_settings:
  font_embed: '<link href="https://fonts.googleapis.com/css?family=Lato:300,400,600,700" rel="stylesheet">'
  title_font: '"Lato", sans-serif'
  body_font: '"Lato", sans-serif'
  regular_weight: 400
  bold_weight: 600
  site_title:
    small_size: 25
    medium_size: 30
    large_size: 35
    weight: 700
    letter_spacing: -0.02
  menu:
    small_size: 30
    medium_size: 15
    large_size: 17
    weight: 600
    letter_spacing: 0
  h1:
    small_size: 35
    medium_size: 45
    large_size: 60
    weight: 700
    letter_spacing: -0.03
    line_height: 1.2
  h2:
    small_size: 22
    medium_size: 30
    large_size: 35
    weight: 700
    letter_spacing: -0.02
    line_height: 1.2
  h3:
    small_size: 22
    medium_size: 25
    large_size: 30
    weight: 600
    letter_spacing: -0.02
    line_height: 1.3
  h4:
    small_size: 17
    medium_size: 22
    large_size: 22
    weight: 700
    letter_spacing: 0
    line_height: 1.6
  h5:
    small_size: 17
    medium_size: 20
    large_size: 20
    weight: 700
    letter_spacing: 0
    line_height: 1.6
  h6:
    small_size: 17
    medium_size: 20
    large_size: 20
    weight: 700
    letter_spacing: 0
    line_height: 1.6
  p:
    small_size: 18
    medium_size: 20
    large_size: 22 # TODO: https://github.com/Egeeio/gsd-cli/issues/13
    weight: 400
    letter_spacing: 0
    line_height: 1.5
  blockquote:
    small_size: 25
    medium_size: 35
    large_size: 45
    weight: 300
    letter_spacing: -0.02
    line_height: 1.6
  buttons:
    weight: 600
    letter_spacing: 0

advanced_settings:
  ajax_loading: true
  analytics_code: ""
  custom_styles: ""
  header_js: ""
  footer_js: ""