# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.5
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Ensure bundler is up to date
          command: |
            gem uninstall bundler
            gem install bundler -v2.0.2
      - run:
          name: Install dependencies
          command: | 
            bundle install
            gem install rspec
      # - run:
      #     name: Run tests
      #     command: rake test
      - run:
          name: Build gemfile
          command: rake build
