title:        Egee.io
tagline:      'Be Different. Play Together.'
url:          https://egee.io
permalink:    pretty
baseurl:      ''
datadomain: egee.io
flattr_id: jj3znl

author:
  name: egee
  url:  https://egee.io

plugins:
  - jekyll-sitemap

exclude:
- README.md
- LICENSE
- Gemfile
- Gemfile.lock
- Rakefile
- .jekyll-cache
- .gitignore
- .editorconfig
